/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ferney.escobar' at '12/7/17 10:09 AM' with Gradle 2.14.1
 *
 * @author ferney.escobar, @date 12/7/17 10:09 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
